"""init tables with cpg schema

Revision ID: 6daa0f06d0f4
Revises: 
Create Date: 2025-11-28 11:15:31.983119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6daa0f06d0f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='cpg'
    )
    op.create_index(op.f('ix_cpg_users_email'), 'users', ['email'], unique=True, schema='cpg')
    op.create_table('posts',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['cpg.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cpg'
    )
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('code_logic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['cpg.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cpg'
    )
    op.create_index(op.f('ix_cpg_strategies_code_logic'), 'strategies', ['code_logic'], unique=False, schema='cpg')
    op.create_index(op.f('ix_cpg_strategies_name'), 'strategies', ['name'], unique=False, schema='cpg')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_index(op.f('ix_cpg_strategies_name'), table_name='strategies', schema='cpg')
    op.drop_index(op.f('ix_cpg_strategies_code_logic'), table_name='strategies', schema='cpg')
    op.drop_table('strategies', schema='cpg')
    op.drop_table('posts', schema='cpg')
    op.drop_index(op.f('ix_cpg_users_email'), table_name='users', schema='cpg')
    op.drop_table('users', schema='cpg')
    # ### end Alembic commands ###
