/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as New_postRouteImport } from './routes/new_post'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostPostIdRouteImport } from './routes/post/$postId'
import { Route as My_workMy_workidRouteImport } from './routes/my_work/$my_workid'
import { Route as AuthAlreadyLoggedInRouteImport } from './routes/auth.already-logged-in'

const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const New_postRoute = New_postRouteImport.update({
  id: '/new_post',
  path: '/new_post',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const My_workMy_workidRoute = My_workMy_workidRouteImport.update({
  id: '/my_work/$my_workid',
  path: '/my_work/$my_workid',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAlreadyLoggedInRoute = AuthAlreadyLoggedInRouteImport.update({
  id: '/auth/already-logged-in',
  path: '/auth/already-logged-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new_post': typeof New_postRoute
  '/posts': typeof PostsRoute
  '/register': typeof RegisterRoute
  '/trades': typeof TradesRoute
  '/auth/already-logged-in': typeof AuthAlreadyLoggedInRoute
  '/my_work/$my_workid': typeof My_workMy_workidRoute
  '/post/$postId': typeof PostPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new_post': typeof New_postRoute
  '/posts': typeof PostsRoute
  '/register': typeof RegisterRoute
  '/trades': typeof TradesRoute
  '/auth/already-logged-in': typeof AuthAlreadyLoggedInRoute
  '/my_work/$my_workid': typeof My_workMy_workidRoute
  '/post/$postId': typeof PostPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new_post': typeof New_postRoute
  '/posts': typeof PostsRoute
  '/register': typeof RegisterRoute
  '/trades': typeof TradesRoute
  '/auth/already-logged-in': typeof AuthAlreadyLoggedInRoute
  '/my_work/$my_workid': typeof My_workMy_workidRoute
  '/post/$postId': typeof PostPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/new_post'
    | '/posts'
    | '/register'
    | '/trades'
    | '/auth/already-logged-in'
    | '/my_work/$my_workid'
    | '/post/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/new_post'
    | '/posts'
    | '/register'
    | '/trades'
    | '/auth/already-logged-in'
    | '/my_work/$my_workid'
    | '/post/$postId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/new_post'
    | '/posts'
    | '/register'
    | '/trades'
    | '/auth/already-logged-in'
    | '/my_work/$my_workid'
    | '/post/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  New_postRoute: typeof New_postRoute
  PostsRoute: typeof PostsRoute
  RegisterRoute: typeof RegisterRoute
  TradesRoute: typeof TradesRoute
  AuthAlreadyLoggedInRoute: typeof AuthAlreadyLoggedInRoute
  My_workMy_workidRoute: typeof My_workMy_workidRoute
  PostPostIdRoute: typeof PostPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new_post': {
      id: '/new_post'
      path: '/new_post'
      fullPath: '/new_post'
      preLoaderRoute: typeof New_postRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my_work/$my_workid': {
      id: '/my_work/$my_workid'
      path: '/my_work/$my_workid'
      fullPath: '/my_work/$my_workid'
      preLoaderRoute: typeof My_workMy_workidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/already-logged-in': {
      id: '/auth/already-logged-in'
      path: '/auth/already-logged-in'
      fullPath: '/auth/already-logged-in'
      preLoaderRoute: typeof AuthAlreadyLoggedInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  New_postRoute: New_postRoute,
  PostsRoute: PostsRoute,
  RegisterRoute: RegisterRoute,
  TradesRoute: TradesRoute,
  AuthAlreadyLoggedInRoute: AuthAlreadyLoggedInRoute,
  My_workMy_workidRoute: My_workMy_workidRoute,
  PostPostIdRoute: PostPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
